[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/img/*"
  [headers.values]
	Cache-Control = '''
	public,
  max-age=604800,
	immutable'''

[build]
  command = "npm run generate"
  publish = "build"

[build.environment]
  NODE_VERSION = "24"
  NPM_VERSION = "11"
  NITRO_PRESET = "netlify"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-store"
