backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

logo_url: /img/PHE-logo.svg

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Highlighted", required: false, name: "isHighlighted", widget: "boolean", default: true}
      - label: 'Cover Image'
        name: 'cover'
        widget: 'image'
        media_library:
          config:
            multiple: true
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        field: {label: Image, name: image, widget: image, required: false}
  - name: 'referenciak'
    label: 'Projects'
    format: 'json'
    folder: 'assets/content/referenciak'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - label: "Year"
        name: "year"
        widget: "number"
        default: 2020
        valueType: "int"
        min: 2019
        max: 2100
        step: 1
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options:
          - { label: "Lebonyolítás", value: "IMPL" }
          - { label: "Projektmenedzsment", value: "PM" }
          - { label: "Műszaki ellenőrzés", value: "TS" }
          - { label: "Műszaki tanácsadás", value: "TC" }
          - { label: "Ingatlanfejelsztés", value: "RED" }
      - label: 'Image'
        name: 'image'
        required: false
        widget: 'image'
        allow_multiple: true
        media_library:
          config:
            multiple: true
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        field: {label: Image, name: image, widget: image, required: false}
  - name: 'service'
    label: 'Services'
    format: 'json'
    create: false
    delete: false
    folder: 'assets/content/service'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Tag', name: 'tag', widget: 'hidden' }
      - label: 'Icon'
        name: 'icon'
        widget: 'image'
        allow_multiple: false
        media_library:
          config:
            multiple: false
      - label: 'Image'
        name: 'image'
        required: false
        widget: 'image'
        allow_multiple: true
        media_library:
          config:
            multiple: true
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
