backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

logo_url: /img/PHE-logo.svg

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Highlighted", required: false, name: "isHighlighted", widget: "boolean", default: true}
      - label: 'Cover Image'
        name: 'cover'
        widget: 'image'
        media_library:
          config:
            multiple: true
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'project'
    label: 'Project'
    format: 'json'
    folder: 'assets/content/project'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options:
          - { label: "Lebonyolítás", value: "IMPL" }
          - { label: "Projektmenedzsment", value: "PM" }
          - { label: "Műszaki ellenőrzés", value: "TS" }
          - { label: "Műszaki tanácsadás", value: "TC" }
          - { label: "Ingatlanfejelsztés", value: "RED" }
      - label: 'Image'
        name: 'image'
        required: false
        widget: 'image'
        allow_multiple: true
        media_library:
          config:
            multiple: true
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'Services'
    format: 'json'
    folder: 'assets/content/services'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Icon', name: 'icon', widget: 'string' }
      - { label: 'Tag', name: 'tag', widget: 'string' }
      - label: 'Image'
        name: 'image'
        required: false
        widget: 'image'
        allow_multiple: true
        media_library:
          config:
            multiple: true
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
